# SkyBlock plugin configuration

# === Database Settings ===
database:
  # MySQL connection URL
  url: "jdbc:mysql://localhost:3306/skyblock"
  # Database user
  user: "root"
  # Database password
  pass: ""
  # Maximum number of connections in the pool
  pool: 5

# === Economy Settings ===
economy:
  starting-balance: 100.0   # money new players start with
  currency-symbol: "$"

# === Islands Settings ===
islands:
  world: "skyblock_world"   # name of the world where islands are placed
  spawn-radius: 5000        # maximum distance for island placement
  default-size: 50          # size of each island
  reset-cost: 500           # money required to reset an island

# === GUI Settings ===
gui:
  menu-title: "SkyBlock Menu"
  rows: 3

# === Items Settings ===
items:
  enable-custom-items: true

  # Format for each item:
  # id:
  #   material: MINECRAFT_ITEM
  #   name: "Display Name"
  #   rarity: RARE/EPIC/etc.
  #   stats: { damage: 100, strength: 50, intelligence: 0 }
  #   ability:
  #     name: "Ability Name"
  #     description:
  #       - "Line 1 of description"
  #       - "Line 2 of description"

  ASPECT_OF_THE_END:
    material: DIAMOND_SWORD
    name: "Aspect of the End"
    rarity: RARE
    stats:
      damage: 100
      strength: 100
      intelligence: 0
    ability:
      name: "Instant Transmission"
      description:
        - "Teleport 8 blocks ahead of you."
        - "Your next hit within 5s deals +50 Damage."

  ASPECT_OF_THE_DRAGONS:
    material: DIAMOND_SWORD
    name: "Aspect of the Dragons"
    rarity: LEGENDARY
    stats:
      damage: 225
      strength: 100
    ability:
      name: "Dragon Rage"
      description:
        - "All monsters in front of you take 700 damage."
        - "They are knocked back slightly."

  EMBER_ROD:
    material: BLAZE_ROD
    name: "Ember Rod"
    rarity: EPIC
    stats:
      damage: 80
      strength: 35
    ability:
      name: "Fire Blast"
      description:
        - "Shoots 3 fireballs in front of you."
        - "Deals 100 damage each."
        # === Debug Mode ===
debug: false
