name: Build SkyBlock

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build plugin
        run: gradle build -x test --no-daemon

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SkyBlock
          path: build/libs/*.jar
          
