name: Build SkyBlock

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew shadowJar --no-daemon
  
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SkyBlock
          path: build/libs/*.jar
          
